### ISSUE TITLE
Ability to add different APIs

### ISSUE THREAD

**Issue by lskatz** [dfornika/pubmlst_client#1]
For example it would be helpful to change the API base to `https://bigsdb.pasteur.fr/api`.  I am unsure how many other instances of bigsdb there are out there.

**Comment by dfornika** [comment]
I didn't realize there were other servers out there. Great suggestion.

Should be fairly straightforward to add a `--base-url` flag that defaults to the pubmlst.org URL.

I'll implement this as soon as I can but if you think you can beat me to it then feel free to submit a PR.

**Comment by lskatz** [comment]
I am a newb in python but I gave it a try
